#!/usr/bin/env bash
# COMMIT phase: create branch and PR from scanner output
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="${REPO_ROOT}/.scanner-output"
BRANCH_PREFIX=$(python3 -c "import json; print(json.load(open('${REPO_ROOT}/.skills-scanner.json'))['output']['branch_prefix'])")
DATE=$(date +%Y%m%d)
BRANCH="${BRANCH_PREFIX}-${DATE}"

usage() {
  echo "Usage: scan-and-pr.sh [--scan-only] [--no-pr]"
  echo "  Runs scanner with --extract, commits results, opens PR via gh"
}

SCAN_ONLY=false
NO_PR=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --scan-only) SCAN_ONLY=true; shift ;;
    --no-pr) NO_PR=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

cd "$REPO_ROOT"

echo "=== SCAN + EXTRACT ==="
"${REPO_ROOT}/scripts/scan-skills.sh" --extract

if [[ ! -f "${OUTPUT_DIR}/candidates.json" ]]; then
  echo "No candidates found, nothing to commit"
  exit 0
fi

if [[ "$SCAN_ONLY" == true ]]; then
  echo "Scan-only mode, output in ${OUTPUT_DIR}/"
  exit 0
fi

count=$(python3 -c "import json; print(len(json.load(open('${OUTPUT_DIR}/candidates.json'))))")
if [[ "$count" -eq 0 ]]; then
  echo "No candidates above threshold"
  exit 0
fi

echo "=== COMMIT: ${count} snippets ==="
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# Merge extracted snippets into skills tree (manual review recommended)
python3 <<'PY'
import json, shutil
from pathlib import Path

root = Path(".")
output = root / ".scanner-output"
candidates = json.loads((output / "candidates.json").read_text())

for c in candidates:
    bucket, *_ = c["bucket"].split("/")
    skill = c["bucket"].split("/")[-1] if "/" in c["bucket"] else "laravel"
    # flat bucket paths like php/laravel-permissions
    parts = c["bucket"].split("/")
    dest_base = root / "skills" / parts[0] / parts[1] / "snippets" if len(parts) > 1 else root / "skills" / parts[0] / "laravel" / "snippets"
    src = output / c["bucket"] / "snippets" / c["snippet"]
    if src.exists() and dest_base.parent.exists():
        dest_base.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest_base / c["snippet"])
        print(f"Copied {c['snippet']} -> {dest_base}")
PY

./sync.sh --update-registry

git add skills/ skills.json .scanner-output/candidates.json
git commit -m "$(cat <<EOF
feat(scanner): extract ${count} snippets from local projects

Auto-generated by scan-and-pr.sh on ${DATE}.
Review anonymization before merge.
EOF
)" || { echo "Nothing to commit"; exit 0; }

if [[ "$NO_PR" == true ]]; then
  echo "Branch ${BRANCH} ready, PR skipped"
  exit 0
fi

if command -v gh &>/dev/null; then
  git push -u origin "$BRANCH"
  gh pr create --title "feat(scanner): ${count} new snippets" --body "$(cat <<EOF
## Summary
- Scanner found ${count} candidates above quality threshold
- Snippets anonymized and copied to skills tree
- Registry updated via sync.sh

## Review checklist
- [ ] Namespaces anonymized correctly
- [ ] No project-specific secrets
- [ ] Snippet index.json updated if needed
EOF
)"
else
  echo "gh CLI not found. Branch ${BRANCH} committed locally."
fi
